### ISSUE TITLE
zmq-shim.so "No such file or directory" on installation

### ISSUE THREAD

**Issue by carpdiem** [joeltg/mit-scheme-kernel#11]
Hi,

I'm able to get all the way through the installation steps up to running make inside the mit-scheme-kernel directory, whereupon the make command fails with:

cc -shared -fPIC -o zmq-shim.so zmq-shim.o `pkg-config --libs libzmq` -undefined dynamic_lookup
cc: error: dynamic_lookup: No such file or directory
make: *** [makefile:24: zmq-shim.so] Error 1

Meanwhile, running 'sudo find / -name "zmq-shim.so"' returns no results, and the zeromq installation process didn't seem to produce any errors.

Do you have any advice here?

**Comment by joeltg** [comment]
What version of MIT Scheme are you running? There were some breaking changes in the 9.2 -> 10.1 upgrade in the foreign function interface that might be causing this.

**Comment by carpdiem** [comment]
10.1.15, pulled down from the gnu.org ftp site as described in the installation directions.

**Comment by rtran9** [comment]
Can you try removing `-undefined dynamic_lookup` from https://github.com/joeltg/mit-scheme-kernel/blob/af583f5bad8842eaf811f1cff62cf6780a585ed5/makefile#L24

**Comment by rtran9** [comment]
To update the docker image, here are the changes I had to make to get it it work:

https://github.com/rtran9/jupyter-mit-scheme/tree/upgrade
https://github.com/rtran9/mit-scheme-kernel/tree/ubuntu

**Comment by carpdiem** [comment]
@rtran9 - Many thanks. Adopting your changes to mit-scheme-kernel/makefile solved my problem, and it's working for me now!

**Comment by thomasjm** [comment]
@joeltg I think perhaps `-undefined dynamic_lookup` is a Mac-only compiler option? This same issue is preventing me from compiling on Linux. Any chance it can just be removed?
