### ISSUE TITLE
Unable to find file ... load.scn

### ISSUE THREAD

**Issue by AtheistApe** [joeltg/mit-scheme-kernel#14]
I followed the install instructions exactly but made one change to the makefile to install the kernel to the location of other Jupyter kernels:

DESTDIR=/home/gary/.local/share/jupyter/kernels/mit-scheme

The install worked fine and the mit-scheme kernel was installed to the above directory. However, when I try:

jupyter console --kernel mit-scheme

I get:

;Unable to find file "/usr/local/share/jupyter/kernels/mit-scheme/load.scm" because: File does not exist.
;To continue, call RESTART with an option number:
; (RESTART 3) => Try to find the same file again.
; (RESTART 2) => Try to find a different file.
; (RESTART 1) => Return to read-eval-print level 1.

2 error> 
End of input stream reached.

**Comment by joeltg** [comment]
The Jupyter kernel install path `/usr/local/share/jupyter/kernels/mit-scheme` is also explicitly referenced in [`load.scm`](https://github.com/joeltg/mit-scheme-kernel/blob/master/src/load.scm#L2) *and* in the [`kernel.json`](https://github.com/joeltg/mit-scheme-kernel/blob/master/src/kernel.json#L6).

It'd definitely be better practice to factor those out into some common single parameter, but in the meantime you _should_ be able to just edit those two paths and reinstall.
