### ISSUE TITLE
Conflating ZMQ identity with session ID

### ISSUE THREAD

**Issue by thomasjm** [joeltg/mit-scheme-kernel#3]
This is another issue about this kernel deviating from the Jupyter messaging spec: http://jupyter-client.readthedocs.io/en/latest/messaging.html#the-wire-protocol. 

Every ZMQ message contains one or more ZMQ identities, which are the first blob or blobs of bytes at the beginning of the message. A subsequent blob is the message header, which is a JSON object containing a "session" field, which is a JSON string. The kernel seems to only work properly when these two things are the *same value*, even though the spec doesn't guarantee this. (Possibly this was reverse-engineered from the Python implementation, where they seem to always match.)

If these values are different, the machinery to look up an old session based on the `uuid` in `kernel.scm:get-session` doesn't work properly, resulting in confusing behavior where you can't define things. For example

```
(define foo 42)
--> foo

foo
--> Unbound variable: foo
```

**Comment by joeltg** [comment]
Thanks for opening this. What sort of configuration produces that behavior?

I don't think that sessions are indexed by `uuid`. The `session` record (defined in `shared.scm`) has a `uuid` slot but it's only used for sending messages later.

```scheme
  (define (get-session uuid header)
    (let ((session (cdr (assq 'session header))))
      (or (session-ref session sessions)
         (let ((s (make-session uuid)))
           (set! sessions (cons s sessions))
           s))))
```

Here `session` is the session value from the JSON header, and that's what's passed to `session-ref`. Only if the session isn't found is `uuid` passed to make a new session.

**Comment by thomasjm** [comment]
Not setting the ZMQ socket identity to match the session ID produces the behavior.

We're agreed the `uuid` slot gets filled in with the ZMQ identity, right? (Naming it after that might be a better variable name.)

If you look inside `session-ref`, it's matching based on `session-uuid`:

```
(define session-ref (association-procedure string=? session-uuid))
```

**Comment by joeltg** [comment]
Wow you are right. I did not read `session.scm` closely at all.

This should be fixed now - I renamed `uuid` to `identity` and added separate `id` property to the session records. Thanks for catching this; let me know if it works.
