### ISSUE TITLE
`load` does not work

### ISSUE THREAD

**Issue by amebru** [joeltg/mit-scheme-kernel#5]
Loading files doesn't make the symbols defined in it accessible in the jupyter console. Is there any way to do this?

Here's an example.

     ~ cat t.scm     
    (define c 5)
    (define (g x y) (+ x y))
    (define h (lambda (x y) (* x y)))
     ~ jupyter console --kernel mit-scheme
    Jupyter console 5.2.0
    
    MIT Scheme Kernel
    
    
    In [1]: (load "t.scm")
    Unable to find file "t.scm" because: File does not exist.
    
    In [2]: c
    Unbound variable: c
    
    In [3]: (g 1 2)
    Unbound variable: g
    
    In [4]: (h 1 2)
    Unbound variable: h

**Comment by joeltg** [comment]
There's definitely a way for that to work - I'll look at it later today. 

In the meantime, does it work if you load an absolute path? Like if you replace t.scm in `(load "t.scm")` with the output of `pwd` in the terminal?

**Comment by joeltg** [comment]
Fixed in 0c2c80547fd8a6deb1579fb1388d8c8edef4a072! Thanks for catching this :-)
