### ISSUE TITLE
Cannot find zmq-shim.so when using mit-scheme --library argument

### ISSUE THREAD

**Issue by bchasnov** [joeltg/mit-scheme-kernel#6]
I'm trying to import the scmutils library into the mit-scheme kernel like so

**src/kernel.json**
```
{
       "argv": [
                "mit-scheme",
                "--silent",
---
>               "--library",
>               "/usr/local/scmutils/mit-scheme/lib",
---
                "--eval",
                "(define pathname (working-directory-pathname))",
                "--load",
                "/usr/local/share/jupyter/kernels/mit-scheme/load.scm",
                "--",
                "{connection_file}"
        ],
        "display_name": "MIT Scheme",
        "language": "scheme"
}
```

but it seems to break, failing to find `zmq-shim.so`

```
;Unable to find file "zmq-shim.so" because: No such file in system library path.
```

How do I re-add the zmq-shim library?

**Comment by joeltg** [comment]
Hmm this is strange.

So naively I'd say that you can just copy all the zmq-related files over with `cp /usr/local/lib/mit-scheme-*/zmq-* /usr/local/scmutils/mit-scheme/lib/.`.

But I just tried this, and it seems to work for normal MIT Scheme (I can launch `jupyter console --kernel mit-scheme` and add `(+ 1 2)` and define things) but it hangs if I try to use something from the scmutils library (I can't derive `(D sin)` or ask for `pi`).

Does this happen for you too? I'll keep looking at this.

**Comment by joeltg** [comment]
Success! c10d0a6e68b79a3fabb23d18f4cb113cce0bf775 should fix this. The problem was with scmutils' implementation of `fluid-let`, which caused an infinite loop on any error.

If you pull, add the `--library` flag back into `kernel.json`, rebuild, reinstall, and `cp /usr/local/lib/mit-scheme-*/zmq-* /usr/local/scmutils/mit-scheme/lib/.`, you should be able to use all of scmutils :-)

**Comment by bchasnov** [comment]
Works perfectly! Thanks.
